version: '3'
services:

  notebook:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    volumes:
        - ./models/random-forest/pipeline.py:/notebooks/pipeline.py
    ports:
      - "${PORT_NOTEBOOK}:${PORT_NOTEBOOK}"

  regression-random-forest:
    env_file: .env
    build:
      context: ./models/random-forest
    volumes:
        - ./data:/code/data
        - ./artifacts:/code/artifacts
    ports:
      - "${PORT_RANDOM_FOREST}:${PORT_RANDOM_FOREST}"

  regression-neural-net:
    env_file: .env
    build:
      context: ./models/neural-net
    volumes:
        - ./data:/code/data
        - ./artifacts:/code/artifacts
    ports:
      - "${PORT_NEURAL_NET}:${PORT_NEURAL_NET}"